// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// solution_w_cpp
arma::vec solution_w_cpp(arma::vec solution_v, arma::mat X0_scaled, arma::mat X1_scaled);
RcppExport SEXP SynthHelpers_solution_w_cpp(SEXP solution_vSEXP, SEXP X0_scaledSEXP, SEXP X1_scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type solution_v(solution_vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X0_scaled(X0_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1_scaled(X1_scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(solution_w_cpp(solution_v, X0_scaled, X1_scaled));
    return rcpp_result_gen;
END_RCPP
}
// fn_v_cpp
double fn_v_cpp(arma::vec variables_v, arma::mat X0_scaled, arma::mat X1_scaled, arma::mat Z0, arma::mat Z1);
RcppExport SEXP SynthHelpers_fn_v_cpp(SEXP variables_vSEXP, SEXP X0_scaledSEXP, SEXP X1_scaledSEXP, SEXP Z0SEXP, SEXP Z1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type variables_v(variables_vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X0_scaled(X0_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1_scaled(X1_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z0(Z0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z1(Z1SEXP);
    rcpp_result_gen = Rcpp::wrap(fn_v_cpp(variables_v, X0_scaled, X1_scaled, Z0, Z1));
    return rcpp_result_gen;
END_RCPP
}
